import 'package:quran/core/utils/io.dart';
import 'package:quran/models/surah_model.dart';
import 'package:quran/models/mushaf.dart';

abstract class QuranData {
  static final List<SurahModel> surahs =
      surahData.map(SurahModel.fromJson).toList();

  static final defaultMushaf = madinahMushafV1;

  static final madinahMushafV1 = Mushaf(
    id: MushafScript.hafsMadinahV1,
    englishName: 'Hafs Al-Madina 1441',
    arabicName: 'مصحف المدينة المنورة',
    version: 'V1',
    coverImage: IO.joinFromSupportFolder("data", "cover_images", "madinahV1.png"),
    yearHijri: 1441,
    yearGregorian: 2020,
  );

  static final madinahMushafV2 = Mushaf(
    id: MushafScript.hafsMadinahV2,
    englishName: 'Hafs Al-Madina 1444',
    arabicName: 'مصحف المدينة المنورة',
    version: 'V2',
    coverImage: IO.joinFromSupportFolder("data", "cover_images", "madinahV2.png"),
  );

  static final List<Mushaf> mushafs = [madinahMushafV1, madinahMushafV2];

  /// Contains the verse of each page in the Quran
  static final pageSurahVerse = [
    // [sura, aya]
    [1, 1], [2, 1], [2, 6], [2, 17], [2, 25],
    [2, 30], [2, 38], [2, 49], [2, 58], [2, 62],
    [2, 70], [2, 77], [2, 84], [2, 89], [2, 94],
    [2, 102], [2, 106], [2, 113], [2, 120], [2, 127],
    [2, 135], [2, 142], [2, 146], [2, 154], [2, 164],
    [2, 170], [2, 177], [2, 182], [2, 187], [2, 191],
    [2, 197], [2, 203], [2, 211], [2, 216], [2, 220],
    [2, 225], [2, 231], [2, 234], [2, 238], [2, 246],
    [2, 249], [2, 253], [2, 257], [2, 260], [2, 265],
    [2, 270], [2, 275], [2, 282], [2, 283], [3, 1],
    [3, 10], [3, 16], [3, 23], [3, 30], [3, 38],
    [3, 46], [3, 53], [3, 62], [3, 71], [3, 78],
    [3, 84], [3, 92], [3, 101], [3, 109], [3, 116],
    [3, 122], [3, 133], [3, 141], [3, 149], [3, 154],
    [3, 158], [3, 166], [3, 174], [3, 181], [3, 187],
    [3, 195], [4, 1], [4, 7], [4, 12], [4, 15],
    [4, 20], [4, 24], [4, 27], [4, 34], [4, 38],
    [4, 45], [4, 52], [4, 60], [4, 66], [4, 75],
    [4, 80], [4, 87], [4, 92], [4, 95], [4, 102],
    [4, 106], [4, 114], [4, 122], [4, 128], [4, 135],
    [4, 141], [4, 148], [4, 155], [4, 163], [4, 171],
    [4, 176], [5, 3], [5, 6], [5, 10], [5, 14],
    [5, 18], [5, 24], [5, 32], [5, 37], [5, 42],
    [5, 46], [5, 51], [5, 58], [5, 65], [5, 71],
    [5, 77], [5, 83], [5, 90], [5, 96], [5, 104],
    [5, 109], [5, 114], [6, 1], [6, 9], [6, 19],
    [6, 28], [6, 36], [6, 45], [6, 53], [6, 60],
    [6, 69], [6, 74], [6, 82], [6, 91], [6, 95],
    [6, 102], [6, 111], [6, 119], [6, 125], [6, 132],
    [6, 138], [6, 143], [6, 147], [6, 152], [6, 158],
    [7, 1], [7, 12], [7, 23], [7, 31], [7, 38],
    [7, 44], [7, 52], [7, 58], [7, 68], [7, 74],
    [7, 82], [7, 88], [7, 96], [7, 105], [7, 121],
    [7, 131], [7, 138], [7, 144], [7, 150], [7, 156],
    [7, 160], [7, 164], [7, 171], [7, 179], [7, 188],
    [7, 196], [8, 1], [8, 9], [8, 17], [8, 26],
    [8, 34], [8, 41], [8, 46], [8, 53], [8, 62],
    [8, 70], [9, 1], [9, 7], [9, 14], [9, 21],
    [9, 27], [9, 32], [9, 37], [9, 41], [9, 48],
    [9, 55], [9, 62], [9, 69], [9, 73], [9, 80],
    [9, 87], [9, 94], [9, 100], [9, 107], [9, 112],
    [9, 118], [9, 123], [10, 1], [10, 7], [10, 15],
    [10, 21], [10, 26], [10, 34], [10, 43], [10, 54],
    [10, 62], [10, 71], [10, 79], [10, 89], [10, 98],
    [10, 107], [11, 6], [11, 13], [11, 20], [11, 29],
    [11, 38], [11, 46], [11, 54], [11, 63], [11, 72],
    [11, 82], [11, 89], [11, 98], [11, 109], [11, 118],
    [12, 5], [12, 15], [12, 23], [12, 31], [12, 38],
    [12, 44], [12, 53], [12, 64], [12, 70], [12, 79],
    [12, 87], [12, 96], [12, 104], [13, 1], [13, 6],
    [13, 14], [13, 19], [13, 29], [13, 35], [13, 43],
    [14, 6], [14, 11], [14, 19], [14, 25], [14, 34],
    [14, 43], [15, 1], [15, 16], [15, 32], [15, 52],
    [15, 71], [15, 91], [16, 7], [16, 15], [16, 27],
    [16, 35], [16, 43], [16, 55], [16, 65], [16, 73],
    [16, 80], [16, 88], [16, 94], [16, 103], [16, 111],
    [16, 119], [17, 1], [17, 8], [17, 18], [17, 28],
    [17, 39], [17, 50], [17, 59], [17, 67], [17, 76],
    [17, 87], [17, 97], [17, 105], [18, 5], [18, 16],
    [18, 21], [18, 28], [18, 35], [18, 46], [18, 54],
    [18, 62], [18, 75], [18, 84], [18, 98], [19, 1],
    [19, 12], [19, 26], [19, 39], [19, 52], [19, 65],
    [19, 77], [19, 96], [20, 13], [20, 38], [20, 52],
    [20, 65], [20, 77], [20, 88], [20, 99], [20, 114],
    [20, 126], [21, 1], [21, 11], [21, 25], [21, 36],
    [21, 45], [21, 58], [21, 73], [21, 82], [21, 91],
    [21, 102], [22, 1], [22, 6], [22, 16], [22, 24],
    [22, 31], [22, 39], [22, 47], [22, 56], [22, 65],
    [22, 73], [23, 1], [23, 18], [23, 28], [23, 43],
    [23, 60], [23, 75], [23, 90], [23, 105], [24, 1],
    [24, 11], [24, 21], [24, 28], [24, 32], [24, 37],
    [24, 44], [24, 54], [24, 59], [24, 62], [25, 3],
    [25, 12], [25, 21], [25, 33], [25, 44], [25, 56],
    [25, 68], [26, 1], [26, 20], [26, 40], [26, 61],
    [26, 84], [26, 112], [26, 137], [26, 160], [26, 184],
    [26, 207], [27, 1], [27, 14], [27, 23], [27, 36],
    [27, 45], [27, 56], [27, 64], [27, 77], [27, 89],
    [28, 6], [28, 14], [28, 22], [28, 29], [28, 36],
    [28, 44], [28, 51], [28, 60], [28, 71], [28, 78],
    [28, 85], [29, 7], [29, 15], [29, 24], [29, 31],
    [29, 39], [29, 46], [29, 53], [29, 64], [30, 6],
    [30, 16], [30, 25], [30, 33], [30, 42], [30, 51],
    [31, 1], [31, 12], [31, 20], [31, 29], [32, 1],
    [32, 12], [32, 21], [33, 1], [33, 7], [33, 16],
    [33, 23], [33, 31], [33, 36], [33, 44], [33, 51],
    [33, 55], [33, 63], [34, 1], [34, 8], [34, 15],
    [34, 23], [34, 32], [34, 40], [34, 49], [35, 4],
    [35, 12], [35, 19], [35, 31], [35, 39], [35, 45],
    [36, 13], [36, 28], [36, 41], [36, 55], [36, 71],
    [37, 1], [37, 25], [37, 52], [37, 77], [37, 103],
    [37, 127], [37, 154], [38, 1], [38, 17], [38, 27],
    [38, 43], [38, 62], [38, 84], [39, 6], [39, 11],
    [39, 22], [39, 32], [39, 41], [39, 48], [39, 57],
    [39, 68], [39, 75], [40, 8], [40, 17], [40, 26],
    [40, 34], [40, 41], [40, 50], [40, 59], [40, 67],
    [40, 78], [41, 1], [41, 12], [41, 21], [41, 30],
    [41, 39], [41, 47], [42, 1], [42, 11], [42, 16],
    [42, 23], [42, 32], [42, 45], [42, 52], [43, 11],
    [43, 23], [43, 34], [43, 48], [43, 61], [43, 74],
    [44, 1], [44, 19], [44, 40], [45, 1], [45, 14],
    [45, 23], [45, 33], [46, 6], [46, 15], [46, 21],
    [46, 29], [47, 1], [47, 12], [47, 20], [47, 30],
    [48, 1], [48, 10], [48, 16], [48, 24], [48, 29],
    [49, 5], [49, 12], [50, 1], [50, 16], [50, 36],
    [51, 7], [51, 31], [51, 52], [52, 15], [52, 32],
    [53, 1], [53, 27], [53, 45], [54, 7], [54, 28],
    [54, 50], [55, 17], [55, 41], [55, 68], [56, 17],
    [56, 51], [56, 77], [57, 4], [57, 12], [57, 19],
    [57, 25], [58, 1], [58, 7], [58, 12], [58, 22],
    [59, 4], [59, 10], [59, 17], [60, 1], [60, 6],
    [60, 12], [61, 6], [62, 1], [62, 9], [63, 5],
    [64, 1], [64, 10], [65, 1], [65, 6], [66, 1],
    [66, 8], [67, 1], [67, 13], [67, 27], [68, 16],
    [68, 43], [69, 9], [69, 35], [70, 11], [70, 40],
    [71, 11], [72, 1], [72, 14], [73, 1], [73, 20],
    [74, 18], [74, 48], [75, 20], [76, 6], [76, 26],
    [77, 20], [78, 1], [78, 31], [79, 16], [80, 1],
    [81, 1], [82, 1], [83, 7], [83, 35], [85, 1],
    [86, 1], [87, 16], [89, 1], [89, 24], [91, 1],
    [92, 15], [95, 1], [97, 1], [98, 8], [100, 10],
    [103, 1], [106, 1], [109, 1], [112, 1],
  ];

  static const surahData = [
    {
      "id": 1,
      "surah_number": 1,
      "bismillah_pre": false,
      "revelation_order": 5,
      "revelation_place": "مكية",
      "name_complex": "Al-Fātiĥah",
      "name_arabic": "الفاتحة",
      "name_simple": "Al-Fatihah",
      "verses_count": 7,
      "pages": [1, 1],
      "translated_name": {"language_name": "english", "name": "The Opener"},
    },
    {
      "id": 2,
      "surah_number": 2,
      "bismillah_pre": true,
      "revelation_order": 87,
      "revelation_place": "مدنية",
      "name_complex": "Al-Baqarah",
      "name_arabic": "البقرة",
      "name_simple": "Al-Baqarah",
      "verses_count": 286,
      "pages": [2, 49],
      "translated_name": {"language_name": "english", "name": "The Cow"},
    },
    {
      "id": 3,
      "surah_number": 3,
      "bismillah_pre": true,
      "revelation_order": 89,
      "revelation_place": "مدنية",
      "name_complex": "Āli `Imrān",
      "name_arabic": "آل عمران",
      "name_simple": "Ali 'Imran",
      "verses_count": 200,
      "pages": [50, 76],
      "translated_name": {
        "language_name": "english",
        "name": "Family of Imran",
      },
    },
    {
      "id": 4,
      "surah_number": 4,
      "bismillah_pre": true,
      "revelation_order": 92,
      "revelation_place": "مدنية",
      "name_complex": "An-Nisā",
      "name_arabic": "النساء",
      "name_simple": "An-Nisa",
      "verses_count": 176,
      "pages": [77, 106],
      "translated_name": {"language_name": "english", "name": "The Women"},
    },
    {
      "id": 5,
      "surah_number": 5,
      "bismillah_pre": true,
      "revelation_order": 112,
      "revelation_place": "مدنية",
      "name_complex": "Al-Mā'idah",
      "name_arabic": "المائدة",
      "name_simple": "Al-Ma'idah",
      "verses_count": 120,
      "pages": [106, 127],
      "translated_name": {
        "language_name": "english",
        "name": "The Table Spread",
      },
    },
    {
      "id": 6,
      "surah_number": 6,
      "bismillah_pre": true,
      "revelation_order": 55,
      "revelation_place": "مكية",
      "name_complex": "Al-'An`ām",
      "name_arabic": "الأنعام",
      "name_simple": "Al-An'am",
      "verses_count": 165,
      "pages": [128, 150],
      "translated_name": {"language_name": "english", "name": "The Cattle"},
    },
    {
      "id": 7,
      "surah_number": 7,
      "bismillah_pre": true,
      "revelation_order": 39,
      "revelation_place": "مكية",
      "name_complex": "Al-'A`rāf",
      "name_arabic": "الأعراف",
      "name_simple": "Al-A'raf",
      "verses_count": 206,
      "pages": [151, 176],
      "translated_name": {"language_name": "english", "name": "The Heights"},
    },
    {
      "id": 8,
      "surah_number": 8,
      "bismillah_pre": true,
      "revelation_order": 88,
      "revelation_place": "مدنية",
      "name_complex": "Al-'Anfāl",
      "name_arabic": "الأنفال",
      "name_simple": "Al-Anfal",
      "verses_count": 75,
      "pages": [177, 186],
      "translated_name": {
        "language_name": "english",
        "name": "The Spoils of War",
      },
    },
    {
      "id": 9,
      "surah_number": 9,
      "bismillah_pre": false,
      "revelation_order": 113,
      "revelation_place": "مدنية",
      "name_complex": "At-Tawbah",
      "name_arabic": "التوبة",
      "name_simple": "At-Tawbah",
      "verses_count": 129,
      "pages": [187, 207],
      "translated_name": {"language_name": "english", "name": "The Repentance"},
    },
    {
      "id": 10,
      "surah_number": 10,
      "bismillah_pre": true,
      "revelation_order": 51,
      "revelation_place": "مكية",
      "name_complex": "Yūnus",
      "name_arabic": "يونس",
      "name_simple": "Yunus",
      "verses_count": 109,
      "pages": [208, 221],
      "translated_name": {"language_name": "english", "name": "Jonah"},
    },
    {
      "id": 11,
      "surah_number": 11,
      "bismillah_pre": true,
      "revelation_order": 52,
      "revelation_place": "مكية",
      "name_complex": "Hūd",
      "name_arabic": "هود",
      "name_simple": "Hud",
      "verses_count": 123,
      "pages": [221, 235],
      "translated_name": {"language_name": "english", "name": "Hud"},
    },
    {
      "id": 12,
      "surah_number": 12,
      "bismillah_pre": true,
      "revelation_order": 53,
      "revelation_place": "مكية",
      "name_complex": "Yūsuf",
      "name_arabic": "يوسف",
      "name_simple": "Yusuf",
      "verses_count": 111,
      "pages": [235, 248],
      "translated_name": {"language_name": "english", "name": "Joseph"},
    },
    {
      "id": 13,
      "surah_number": 13,
      "bismillah_pre": true,
      "revelation_order": 96,
      "revelation_place": "مدنية",
      "name_complex": "Ar-Ra`d",
      "name_arabic": "الرعد",
      "name_simple": "Ar-Ra'd",
      "verses_count": 43,
      "pages": [249, 255],
      "translated_name": {"language_name": "english", "name": "The Thunder"},
    },
    {
      "id": 14,
      "surah_number": 14,
      "bismillah_pre": true,
      "revelation_order": 72,
      "revelation_place": "مكية",
      "name_complex": "Ibrāhīm",
      "name_arabic": "ابراهيم",
      "name_simple": "Ibrahim",
      "verses_count": 52,
      "pages": [255, 261],
      "translated_name": {"language_name": "english", "name": "Abrahim"},
    },
    {
      "id": 15,
      "surah_number": 15,
      "bismillah_pre": true,
      "revelation_order": 54,
      "revelation_place": "مكية",
      "name_complex": "Al-Ĥijr",
      "name_arabic": "الحجر",
      "name_simple": "Al-Hijr",
      "verses_count": 99,
      "pages": [262, 267],
      "translated_name": {
        "language_name": "english",
        "name": "The Rocky Tract",
      },
    },
    {
      "id": 16,
      "surah_number": 16,
      "bismillah_pre": true,
      "revelation_order": 70,
      "revelation_place": "مكية",
      "name_complex": "An-Naĥl",
      "name_arabic": "النحل",
      "name_simple": "An-Nahl",
      "verses_count": 128,
      "pages": [267, 281],
      "translated_name": {"language_name": "english", "name": "The Bee"},
    },
    {
      "id": 17,
      "surah_number": 17,
      "bismillah_pre": true,
      "revelation_order": 50,
      "revelation_place": "مكية",
      "name_complex": "Al-'Isrā",
      "name_arabic": "الإسراء",
      "name_simple": "Al-Isra",
      "verses_count": 111,
      "pages": [282, 293],
      "translated_name": {
        "language_name": "english",
        "name": "The Night Journey",
      },
    },
    {
      "id": 18,
      "surah_number": 18,
      "bismillah_pre": true,
      "revelation_order": 69,
      "revelation_place": "مكية",
      "name_complex": "Al-Kahf",
      "name_arabic": "الكهف",
      "name_simple": "Al-Kahf",
      "verses_count": 110,
      "pages": [293, 304],
      "translated_name": {"language_name": "english", "name": "The Cave"},
    },
    {
      "id": 19,
      "surah_number": 19,
      "bismillah_pre": true,
      "revelation_order": 44,
      "revelation_place": "مكية",
      "name_complex": "Maryam",
      "name_arabic": "مريم",
      "name_simple": "Maryam",
      "verses_count": 98,
      "pages": [305, 312],
      "translated_name": {"language_name": "english", "name": "Mary"},
    },
    {
      "id": 20,
      "surah_number": 20,
      "bismillah_pre": true,
      "revelation_order": 45,
      "revelation_place": "مكية",
      "name_complex": "Ţāhā",
      "name_arabic": "طه",
      "name_simple": "Taha",
      "verses_count": 135,
      "pages": [312, 321],
      "translated_name": {"language_name": "english", "name": "Ta-Ha"},
    },
    {
      "id": 21,
      "surah_number": 21,
      "bismillah_pre": true,
      "revelation_order": 73,
      "revelation_place": "مكية",
      "name_complex": "Al-'Anbyā",
      "name_arabic": "الأنبياء",
      "name_simple": "Al-Anbya",
      "verses_count": 112,
      "pages": [322, 331],
      "translated_name": {"language_name": "english", "name": "The Prophets"},
    },
    {
      "id": 22,
      "surah_number": 22,
      "bismillah_pre": true,
      "revelation_order": 103,
      "revelation_place": "مدنية",
      "name_complex": "Al-Ĥaj",
      "name_arabic": "الحج",
      "name_simple": "Al-Haj",
      "verses_count": 78,
      "pages": [332, 341],
      "translated_name": {"language_name": "english", "name": "The Pilgrimage"},
    },
    {
      "id": 23,
      "surah_number": 23,
      "bismillah_pre": true,
      "revelation_order": 74,
      "revelation_place": "مكية",
      "name_complex": "Al-Mu'minūn",
      "name_arabic": "المؤمنون",
      "name_simple": "Al-Mu'minun",
      "verses_count": 118,
      "pages": [342, 349],
      "translated_name": {"language_name": "english", "name": "The Believers"},
    },
    {
      "id": 24,
      "surah_number": 24,
      "bismillah_pre": true,
      "revelation_order": 102,
      "revelation_place": "مدنية",
      "name_complex": "An-Nūr",
      "name_arabic": "النور",
      "name_simple": "An-Nur",
      "verses_count": 64,
      "pages": [350, 359],
      "translated_name": {"language_name": "english", "name": "The Light"},
    },
    {
      "id": 25,
      "surah_number": 25,
      "bismillah_pre": true,
      "revelation_order": 42,
      "revelation_place": "مكية",
      "name_complex": "Al-Furqān",
      "name_arabic": "الفرقان",
      "name_simple": "Al-Furqan",
      "verses_count": 77,
      "pages": [359, 366],
      "translated_name": {"language_name": "english", "name": "The Criterian"},
    },
    {
      "id": 26,
      "surah_number": 26,
      "bismillah_pre": true,
      "revelation_order": 47,
      "revelation_place": "مكية",
      "name_complex": "Ash-Shu`arā",
      "name_arabic": "الشعراء",
      "name_simple": "Ash-Shu'ara",
      "verses_count": 227,
      "pages": [367, 376],
      "translated_name": {"language_name": "english", "name": "The Poets"},
    },
    {
      "id": 27,
      "surah_number": 27,
      "bismillah_pre": true,
      "revelation_order": 48,
      "revelation_place": "مكية",
      "name_complex": "An-Naml",
      "name_arabic": "النمل",
      "name_simple": "An-Naml",
      "verses_count": 93,
      "pages": [377, 385],
      "translated_name": {"language_name": "english", "name": "The Ant"},
    },
    {
      "id": 28,
      "surah_number": 28,
      "bismillah_pre": true,
      "revelation_order": 49,
      "revelation_place": "مكية",
      "name_complex": "Al-Qaşaş",
      "name_arabic": "القصص",
      "name_simple": "Al-Qasas",
      "verses_count": 88,
      "pages": [385, 396],
      "translated_name": {"language_name": "english", "name": "The Stories"},
    },
    {
      "id": 29,
      "surah_number": 29,
      "bismillah_pre": true,
      "revelation_order": 85,
      "revelation_place": "مكية",
      "name_complex": "Al-`Ankabūt",
      "name_arabic": "العنكبوت",
      "name_simple": "Al-'Ankabut",
      "verses_count": 69,
      "pages": [396, 404],
      "translated_name": {"language_name": "english", "name": "The Spider"},
    },
    {
      "id": 30,
      "surah_number": 30,
      "bismillah_pre": true,
      "revelation_order": 84,
      "revelation_place": "مكية",
      "name_complex": "Ar-Rūm",
      "name_arabic": "الروم",
      "name_simple": "Ar-Rum",
      "verses_count": 60,
      "pages": [404, 410],
      "translated_name": {"language_name": "english", "name": "The Romans"},
    },
    {
      "id": 31,
      "surah_number": 31,
      "bismillah_pre": true,
      "revelation_order": 57,
      "revelation_place": "مكية",
      "name_complex": "Luqmān",
      "name_arabic": "لقمان",
      "name_simple": "Luqman",
      "verses_count": 34,
      "pages": [411, 414],
      "translated_name": {"language_name": "english", "name": "Luqman"},
    },
    {
      "id": 32,
      "surah_number": 32,
      "bismillah_pre": true,
      "revelation_order": 75,
      "revelation_place": "مكية",
      "name_complex": "As-Sajdah",
      "name_arabic": "السجدة",
      "name_simple": "As-Sajdah",
      "verses_count": 30,
      "pages": [415, 417],
      "translated_name": {
        "language_name": "english",
        "name": "The Prostration",
      },
    },
    {
      "id": 33,
      "surah_number": 33,
      "bismillah_pre": true,
      "revelation_order": 90,
      "revelation_place": "مدنية",
      "name_complex": "Al-'Aĥzāb",
      "name_arabic": "الأحزاب",
      "name_simple": "Al-Ahzab",
      "verses_count": 73,
      "pages": [418, 427],
      "translated_name": {
        "language_name": "english",
        "name": "The Combined Forces",
      },
    },
    {
      "id": 34,
      "surah_number": 34,
      "bismillah_pre": true,
      "revelation_order": 58,
      "revelation_place": "مكية",
      "name_complex": "Saba",
      "name_arabic": "سبإ",
      "name_simple": "Saba",
      "verses_count": 54,
      "pages": [428, 434],
      "translated_name": {"language_name": "english", "name": "Sheba"},
    },
    {
      "id": 35,
      "surah_number": 35,
      "bismillah_pre": true,
      "revelation_order": 43,
      "revelation_place": "مكية",
      "name_complex": "Fāţir",
      "name_arabic": "فاطر",
      "name_simple": "Fatir",
      "verses_count": 45,
      "pages": [434, 440],
      "translated_name": {"language_name": "english", "name": "Originator"},
    },
    {
      "id": 36,
      "surah_number": 36,
      "bismillah_pre": true,
      "revelation_order": 41,
      "revelation_place": "مكية",
      "name_complex": "Yā-Sīn",
      "name_arabic": "يس",
      "name_simple": "Ya-Sin",
      "verses_count": 83,
      "pages": [440, 445],
      "translated_name": {"language_name": "english", "name": "Ya Sin"},
    },
    {
      "id": 37,
      "surah_number": 37,
      "bismillah_pre": true,
      "revelation_order": 56,
      "revelation_place": "مكية",
      "name_complex": "Aş-Şāffāt",
      "name_arabic": "الصافات",
      "name_simple": "As-Saffat",
      "verses_count": 182,
      "pages": [446, 452],
      "translated_name": {
        "language_name": "english",
        "name": "Those who set the Ranks",
      },
    },
    {
      "id": 38,
      "surah_number": 38,
      "bismillah_pre": true,
      "revelation_order": 38,
      "revelation_place": "مكية",
      "name_complex": "Şād",
      "name_arabic": "ص",
      "name_simple": "Sad",
      "verses_count": 88,
      "pages": [453, 458],
      "translated_name": {
        "language_name": "english",
        "name": "The Letter \"Saad\"",
      },
    },
    {
      "id": 39,
      "surah_number": 39,
      "bismillah_pre": true,
      "revelation_order": 59,
      "revelation_place": "مكية",
      "name_complex": "Az-Zumar",
      "name_arabic": "الزمر",
      "name_simple": "Az-Zumar",
      "verses_count": 75,
      "pages": [458, 467],
      "translated_name": {"language_name": "english", "name": "The Troops"},
    },
    {
      "id": 40,
      "surah_number": 40,
      "bismillah_pre": true,
      "revelation_order": 60,
      "revelation_place": "مكية",
      "name_complex": "Ghāfir",
      "name_arabic": "غافر",
      "name_simple": "Ghafir",
      "verses_count": 85,
      "pages": [467, 476],
      "translated_name": {"language_name": "english", "name": "The Forgiver"},
    },
    {
      "id": 41,
      "surah_number": 41,
      "bismillah_pre": true,
      "revelation_order": 61,
      "revelation_place": "مكية",
      "name_complex": "Fuşşilat",
      "name_arabic": "فصلت",
      "name_simple": "Fussilat",
      "verses_count": 54,
      "pages": [477, 482],
      "translated_name": {
        "language_name": "english",
        "name": "Explained in Detail",
      },
    },
    {
      "id": 42,
      "surah_number": 42,
      "bismillah_pre": true,
      "revelation_order": 62,
      "revelation_place": "مكية",
      "name_complex": "Ash-Shūraá",
      "name_arabic": "الشورى",
      "name_simple": "Ash-Shuraa",
      "verses_count": 53,
      "pages": [483, 489],
      "translated_name": {
        "language_name": "english",
        "name": "The Consultation",
      },
    },
    {
      "id": 43,
      "surah_number": 43,
      "bismillah_pre": true,
      "revelation_order": 63,
      "revelation_place": "مكية",
      "name_complex": "Az-Zukhruf",
      "name_arabic": "الزخرف",
      "name_simple": "Az-Zukhruf",
      "verses_count": 89,
      "pages": [489, 495],
      "translated_name": {
        "language_name": "english",
        "name": "The Ornaments of Gold",
      },
    },
    {
      "id": 44,
      "surah_number": 44,
      "bismillah_pre": true,
      "revelation_order": 64,
      "revelation_place": "مكية",
      "name_complex": "Ad-Dukhān",
      "name_arabic": "الدخان",
      "name_simple": "Ad-Dukhan",
      "verses_count": 59,
      "pages": [496, 498],
      "translated_name": {"language_name": "english", "name": "The Smoke"},
    },
    {
      "id": 45,
      "surah_number": 45,
      "bismillah_pre": true,
      "revelation_order": 65,
      "revelation_place": "مكية",
      "name_complex": "Al-Jāthiyah",
      "name_arabic": "الجاثية",
      "name_simple": "Al-Jathiyah",
      "verses_count": 37,
      "pages": [499, 502],
      "translated_name": {"language_name": "english", "name": "The Crouching"},
    },
    {
      "id": 46,
      "surah_number": 46,
      "bismillah_pre": true,
      "revelation_order": 66,
      "revelation_place": "مكية",
      "name_complex": "Al-'Aĥqāf",
      "name_arabic": "الأحقاف",
      "name_simple": "Al-Ahqaf",
      "verses_count": 35,
      "pages": [502, 506],
      "translated_name": {
        "language_name": "english",
        "name": "The Wind-Curved Sandhills",
      },
    },
    {
      "id": 47,
      "surah_number": 47,
      "bismillah_pre": true,
      "revelation_order": 95,
      "revelation_place": "مدنية",
      "name_complex": "Muĥammad",
      "name_arabic": "محمد",
      "name_simple": "Muhammad",
      "verses_count": 38,
      "pages": [507, 510],
      "translated_name": {"language_name": "english", "name": "Muhammad"},
    },
    {
      "id": 48,
      "surah_number": 48,
      "bismillah_pre": true,
      "revelation_order": 111,
      "revelation_place": "مدنية",
      "name_complex": "Al-Fatĥ",
      "name_arabic": "الفتح",
      "name_simple": "Al-Fath",
      "verses_count": 29,
      "pages": [511, 515],
      "translated_name": {"language_name": "english", "name": "The Victory"},
    },
    {
      "id": 49,
      "surah_number": 49,
      "bismillah_pre": true,
      "revelation_order": 106,
      "revelation_place": "مدنية",
      "name_complex": "Al-Ĥujurāt",
      "name_arabic": "الحجرات",
      "name_simple": "Al-Hujurat",
      "verses_count": 18,
      "pages": [515, 517],
      "translated_name": {"language_name": "english", "name": "The Rooms"},
    },
    {
      "id": 50,
      "surah_number": 50,
      "bismillah_pre": true,
      "revelation_order": 34,
      "revelation_place": "مكية",
      "name_complex": "Qāf",
      "name_arabic": "ق",
      "name_simple": "Qaf",
      "verses_count": 45,
      "pages": [518, 520],
      "translated_name": {
        "language_name": "english",
        "name": "The Letter \"Qaf\"",
      },
    },
    {
      "id": 51,
      "surah_number": 51,
      "bismillah_pre": true,
      "revelation_order": 67,
      "revelation_place": "مكية",
      "name_complex": "Adh-Dhāriyāt",
      "name_arabic": "الذاريات",
      "name_simple": "Adh-Dhariyat",
      "verses_count": 60,
      "pages": [520, 523],
      "translated_name": {
        "language_name": "english",
        "name": "The Winnowing Winds",
      },
    },
    {
      "id": 52,
      "surah_number": 52,
      "bismillah_pre": true,
      "revelation_order": 76,
      "revelation_place": "مكية",
      "name_complex": "Aţ-Ţūr",
      "name_arabic": "الطور",
      "name_simple": "At-Tur",
      "verses_count": 49,
      "pages": [523, 525],
      "translated_name": {"language_name": "english", "name": "The Mount"},
    },
    {
      "id": 53,
      "surah_number": 53,
      "bismillah_pre": true,
      "revelation_order": 23,
      "revelation_place": "مكية",
      "name_complex": "An-Najm",
      "name_arabic": "النجم",
      "name_simple": "An-Najm",
      "verses_count": 62,
      "pages": [526, 528],
      "translated_name": {"language_name": "english", "name": "The Star"},
    },
    {
      "id": 54,
      "surah_number": 54,
      "bismillah_pre": true,
      "revelation_order": 37,
      "revelation_place": "مكية",
      "name_complex": "Al-Qamar",
      "name_arabic": "القمر",
      "name_simple": "Al-Qamar",
      "verses_count": 55,
      "pages": [528, 531],
      "translated_name": {"language_name": "english", "name": "The Moon"},
    },
    {
      "id": 55,
      "surah_number": 55,
      "bismillah_pre": true,
      "revelation_order": 97,
      "revelation_place": "مدنية",
      "name_complex": "Ar-Raĥmān",
      "name_arabic": "الرحمن",
      "name_simple": "Ar-Rahman",
      "verses_count": 78,
      "pages": [531, 534],
      "translated_name": {"language_name": "english", "name": "The Beneficent"},
    },
    {
      "id": 56,
      "surah_number": 56,
      "bismillah_pre": true,
      "revelation_order": 46,
      "revelation_place": "مكية",
      "name_complex": "Al-Wāqi`ah",
      "name_arabic": "الواقعة",
      "name_simple": "Al-Waqi'ah",
      "verses_count": 96,
      "pages": [534, 537],
      "translated_name": {"language_name": "english", "name": "The Inevitable"},
    },
    {
      "id": 57,
      "surah_number": 57,
      "bismillah_pre": true,
      "revelation_order": 94,
      "revelation_place": "مدنية",
      "name_complex": "Al-Ĥadīd",
      "name_arabic": "الحديد",
      "name_simple": "Al-Hadid",
      "verses_count": 29,
      "pages": [537, 541],
      "translated_name": {"language_name": "english", "name": "The Iron"},
    },
    {
      "id": 58,
      "surah_number": 58,
      "bismillah_pre": true,
      "revelation_order": 105,
      "revelation_place": "مدنية",
      "name_complex": "Al-Mujādila",
      "name_arabic": "المجادلة",
      "name_simple": "Al-Mujadila",
      "verses_count": 22,
      "pages": [542, 545],
      "translated_name": {
        "language_name": "english",
        "name": "The Pleading Woman",
      },
    },
    {
      "id": 59,
      "surah_number": 59,
      "bismillah_pre": true,
      "revelation_order": 101,
      "revelation_place": "مدنية",
      "name_complex": "Al-Ĥashr",
      "name_arabic": "الحشر",
      "name_simple": "Al-Hashr",
      "verses_count": 24,
      "pages": [545, 548],
      "translated_name": {"language_name": "english", "name": "The Exile"},
    },
    {
      "id": 60,
      "surah_number": 60,
      "bismillah_pre": true,
      "revelation_order": 91,
      "revelation_place": "مدنية",
      "name_complex": "Al-Mumtaĥanah",
      "name_arabic": "الممتحنة",
      "name_simple": "Al-Mumtahanah",
      "verses_count": 13,
      "pages": [549, 551],
      "translated_name": {
        "language_name": "english",
        "name": "She that is to be examined",
      },
    },
    {
      "id": 61,
      "surah_number": 61,
      "bismillah_pre": true,
      "revelation_order": 109,
      "revelation_place": "مدنية",
      "name_complex": "Aş-Şaf",
      "name_arabic": "الصف",
      "name_simple": "As-Saf",
      "verses_count": 14,
      "pages": [551, 552],
      "translated_name": {"language_name": "english", "name": "The Ranks"},
    },
    {
      "id": 62,
      "surah_number": 62,
      "bismillah_pre": true,
      "revelation_order": 110,
      "revelation_place": "مدنية",
      "name_complex": "Al-Jumu`ah",
      "name_arabic": "الجمعة",
      "name_simple": "Al-Jumu'ah",
      "verses_count": 11,
      "pages": [553, 554],
      "translated_name": {
        "language_name": "english",
        "name": "The Congregation, Friday",
      },
    },
    {
      "id": 63,
      "surah_number": 63,
      "bismillah_pre": true,
      "revelation_order": 104,
      "revelation_place": "مدنية",
      "name_complex": "Al-Munāfiqūn",
      "name_arabic": "المنافقون",
      "name_simple": "Al-Munafiqun",
      "verses_count": 11,
      "pages": [554, 555],
      "translated_name": {"language_name": "english", "name": "The Hypocrites"},
    },
    {
      "id": 64,
      "surah_number": 64,
      "bismillah_pre": true,
      "revelation_order": 108,
      "revelation_place": "مدنية",
      "name_complex": "At-Taghābun",
      "name_arabic": "التغابن",
      "name_simple": "At-Taghabun",
      "verses_count": 18,
      "pages": [556, 557],
      "translated_name": {
        "language_name": "english",
        "name": "The Mutual Disillusion",
      },
    },
    {
      "id": 65,
      "surah_number": 65,
      "bismillah_pre": true,
      "revelation_order": 99,
      "revelation_place": "مدنية",
      "name_complex": "Aţ-Ţalāq",
      "name_arabic": "الطلاق",
      "name_simple": "At-Talaq",
      "verses_count": 12,
      "pages": [558, 559],
      "translated_name": {"language_name": "english", "name": "The Divorce"},
    },
    {
      "id": 66,
      "surah_number": 66,
      "bismillah_pre": true,
      "revelation_order": 107,
      "revelation_place": "مدنية",
      "name_complex": "At-Taĥrīm",
      "name_arabic": "التحريم",
      "name_simple": "At-Tahrim",
      "verses_count": 12,
      "pages": [560, 561],
      "translated_name": {
        "language_name": "english",
        "name": "The Prohibtiion",
      },
    },
    {
      "id": 67,
      "surah_number": 67,
      "bismillah_pre": true,
      "revelation_order": 77,
      "revelation_place": "مكية",
      "name_complex": "Al-Mulk",
      "name_arabic": "الملك",
      "name_simple": "Al-Mulk",
      "verses_count": 30,
      "pages": [562, 564],
      "translated_name": {
        "language_name": "english",
        "name": "The Sovereignty",
      },
    },
    {
      "id": 68,
      "surah_number": 68,
      "bismillah_pre": true,
      "revelation_order": 2,
      "revelation_place": "مكية",
      "name_complex": "Al-Qalam",
      "name_arabic": "القلم",
      "name_simple": "Al-Qalam",
      "verses_count": 52,
      "pages": [564, 566],
      "translated_name": {"language_name": "english", "name": "The Pen"},
    },
    {
      "id": 69,
      "surah_number": 69,
      "bismillah_pre": true,
      "revelation_order": 78,
      "revelation_place": "مكية",
      "name_complex": "Al-Ĥāqqah",
      "name_arabic": "الحاقة",
      "name_simple": "Al-Haqqah",
      "verses_count": 52,
      "pages": [566, 568],
      "translated_name": {"language_name": "english", "name": "The Reality"},
    },
    {
      "id": 70,
      "surah_number": 70,
      "bismillah_pre": true,
      "revelation_order": 79,
      "revelation_place": "مكية",
      "name_complex": "Al-Ma`ārij",
      "name_arabic": "المعارج",
      "name_simple": "Al-Ma'arij",
      "verses_count": 44,
      "pages": [568, 570],
      "translated_name": {
        "language_name": "english",
        "name": "The Ascending Stairways",
      },
    },
    {
      "id": 71,
      "surah_number": 71,
      "bismillah_pre": true,
      "revelation_order": 71,
      "revelation_place": "مكية",
      "name_complex": "Nūĥ",
      "name_arabic": "نوح",
      "name_simple": "Nuh",
      "verses_count": 28,
      "pages": [570, 571],
      "translated_name": {"language_name": "english", "name": "Noah"},
    },
    {
      "id": 72,
      "surah_number": 72,
      "bismillah_pre": true,
      "revelation_order": 40,
      "revelation_place": "مكية",
      "name_complex": "Al-Jinn",
      "name_arabic": "الجن",
      "name_simple": "Al-Jinn",
      "verses_count": 28,
      "pages": [572, 573],
      "translated_name": {"language_name": "english", "name": "The Jinn"},
    },
    {
      "id": 73,
      "surah_number": 73,
      "bismillah_pre": true,
      "revelation_order": 3,
      "revelation_place": "مكية",
      "name_complex": "Al-Muzzammil",
      "name_arabic": "المزمل",
      "name_simple": "Al-Muzzammil",
      "verses_count": 20,
      "pages": [574, 575],
      "translated_name": {
        "language_name": "english",
        "name": "The Enshrouded One",
      },
    },
    {
      "id": 74,
      "surah_number": 74,
      "bismillah_pre": true,
      "revelation_order": 4,
      "revelation_place": "مكية",
      "name_complex": "Al-Muddaththir",
      "name_arabic": "المدثر",
      "name_simple": "Al-Muddaththir",
      "verses_count": 56,
      "pages": [575, 577],
      "translated_name": {
        "language_name": "english",
        "name": "The Cloaked One",
      },
    },
    {
      "id": 75,
      "surah_number": 75,
      "bismillah_pre": true,
      "revelation_order": 31,
      "revelation_place": "مكية",
      "name_complex": "Al-Qiyāmah",
      "name_arabic": "القيامة",
      "name_simple": "Al-Qiyamah",
      "verses_count": 40,
      "pages": [577, 578],
      "translated_name": {
        "language_name": "english",
        "name": "The Resurrection",
      },
    },
    {
      "id": 76,
      "surah_number": 76,
      "bismillah_pre": true,
      "revelation_order": 98,
      "revelation_place": "مدنية",
      "name_complex": "Al-'Insān",
      "name_arabic": "الانسان",
      "name_simple": "Al-Insan",
      "verses_count": 31,
      "pages": [578, 580],
      "translated_name": {"language_name": "english", "name": "The Man"},
    },
    {
      "id": 77,
      "surah_number": 77,
      "bismillah_pre": true,
      "revelation_order": 33,
      "revelation_place": "مكية",
      "name_complex": "Al-Mursalāt",
      "name_arabic": "المرسلات",
      "name_simple": "Al-Mursalat",
      "verses_count": 50,
      "pages": [580, 581],
      "translated_name": {"language_name": "english", "name": "The Emissaries"},
    },
    {
      "id": 78,
      "surah_number": 78,
      "bismillah_pre": true,
      "revelation_order": 80,
      "revelation_place": "مكية",
      "name_complex": "An-Naba",
      "name_arabic": "النبإ",
      "name_simple": "An-Naba",
      "verses_count": 40,
      "pages": [582, 583],
      "translated_name": {"language_name": "english", "name": "The Tidings"},
    },
    {
      "id": 79,
      "surah_number": 79,
      "bismillah_pre": true,
      "revelation_order": 81,
      "revelation_place": "مكية",
      "name_complex": "An-Nāzi`āt",
      "name_arabic": "النازعات",
      "name_simple": "An-Nazi'at",
      "verses_count": 46,
      "pages": [583, 584],
      "translated_name": {
        "language_name": "english",
        "name": "Those who drag forth",
      },
    },
    {
      "id": 80,
      "surah_number": 80,
      "bismillah_pre": true,
      "revelation_order": 24,
      "revelation_place": "مكية",
      "name_complex": "`Abasa",
      "name_arabic": "عبس",
      "name_simple": "'Abasa",
      "verses_count": 42,
      "pages": [585, 585],
      "translated_name": {"language_name": "english", "name": "He Frowned"},
    },
    {
      "id": 81,
      "surah_number": 81,
      "bismillah_pre": true,
      "revelation_order": 7,
      "revelation_place": "مكية",
      "name_complex": "At-Takwīr",
      "name_arabic": "التكوير",
      "name_simple": "At-Takwir",
      "verses_count": 29,
      "pages": [586, 586],
      "translated_name": {
        "language_name": "english",
        "name": "The Overthrowing",
      },
    },
    {
      "id": 82,
      "surah_number": 82,
      "bismillah_pre": true,
      "revelation_order": 82,
      "revelation_place": "مكية",
      "name_complex": "Al-'Infiţār",
      "name_arabic": "الإنفطار",
      "name_simple": "Al-Infitar",
      "verses_count": 19,
      "pages": [587, 587],
      "translated_name": {"language_name": "english", "name": "The Cleaving"},
    },
    {
      "id": 83,
      "surah_number": 83,
      "bismillah_pre": true,
      "revelation_order": 86,
      "revelation_place": "مكية",
      "name_complex": "Al-Muţaffifīn",
      "name_arabic": "المطففين",
      "name_simple": "Al-Mutaffifin",
      "verses_count": 36,
      "pages": [587, 589],
      "translated_name": {"language_name": "english", "name": "The Defrauding"},
    },
    {
      "id": 84,
      "surah_number": 84,
      "bismillah_pre": true,
      "revelation_order": 83,
      "revelation_place": "مكية",
      "name_complex": "Al-'Inshiqāq",
      "name_arabic": "الإنشقاق",
      "name_simple": "Al-Inshiqaq",
      "verses_count": 25,
      "pages": [589, 589],
      "translated_name": {"language_name": "english", "name": "The Sundering"},
    },
    {
      "id": 85,
      "surah_number": 85,
      "bismillah_pre": true,
      "revelation_order": 27,
      "revelation_place": "مكية",
      "name_complex": "Al-Burūj",
      "name_arabic": "البروج",
      "name_simple": "Al-Buruj",
      "verses_count": 22,
      "pages": [590, 590],
      "translated_name": {
        "language_name": "english",
        "name": "The Mansions of the Stars",
      },
    },
    {
      "id": 86,
      "surah_number": 86,
      "bismillah_pre": true,
      "revelation_order": 36,
      "revelation_place": "مكية",
      "name_complex": "Aţ-Ţāriq",
      "name_arabic": "الطارق",
      "name_simple": "At-Tariq",
      "verses_count": 17,
      "pages": [591, 591],
      "translated_name": {
        "language_name": "english",
        "name": "The Nightcommer",
      },
    },
    {
      "id": 87,
      "surah_number": 87,
      "bismillah_pre": true,
      "revelation_order": 8,
      "revelation_place": "مكية",
      "name_complex": "Al-'A`lá",
      "name_arabic": "الأعلى",
      "name_simple": "Al-A'la",
      "verses_count": 19,
      "pages": [591, 592],
      "translated_name": {"language_name": "english", "name": "The Most High"},
    },
    {
      "id": 88,
      "surah_number": 88,
      "bismillah_pre": true,
      "revelation_order": 68,
      "revelation_place": "مكية",
      "name_complex": "Al-Ghāshiyah",
      "name_arabic": "الغاشية",
      "name_simple": "Al-Ghashiyah",
      "verses_count": 26,
      "pages": [592, 592],
      "translated_name": {
        "language_name": "english",
        "name": "The Overwhelming",
      },
    },
    {
      "id": 89,
      "surah_number": 89,
      "bismillah_pre": true,
      "revelation_order": 10,
      "revelation_place": "مكية",
      "name_complex": "Al-Fajr",
      "name_arabic": "الفجر",
      "name_simple": "Al-Fajr",
      "verses_count": 30,
      "pages": [593, 594],
      "translated_name": {"language_name": "english", "name": "The Dawn"},
    },
    {
      "id": 90,
      "surah_number": 90,
      "bismillah_pre": true,
      "revelation_order": 35,
      "revelation_place": "مكية",
      "name_complex": "Al-Balad",
      "name_arabic": "البلد",
      "name_simple": "Al-Balad",
      "verses_count": 20,
      "pages": [594, 594],
      "translated_name": {"language_name": "english", "name": "The City"},
    },
    {
      "id": 91,
      "surah_number": 91,
      "bismillah_pre": true,
      "revelation_order": 26,
      "revelation_place": "مكية",
      "name_complex": "Ash-Shams",
      "name_arabic": "الشمس",
      "name_simple": "Ash-Shams",
      "verses_count": 15,
      "pages": [595, 595],
      "translated_name": {"language_name": "english", "name": "The Sun"},
    },
    {
      "id": 92,
      "surah_number": 92,
      "bismillah_pre": true,
      "revelation_order": 9,
      "revelation_place": "مكية",
      "name_complex": "Al-Layl",
      "name_arabic": "الليل",
      "name_simple": "Al-Layl",
      "verses_count": 21,
      "pages": [595, 596],
      "translated_name": {"language_name": "english", "name": "The Night"},
    },
    {
      "id": 93,
      "surah_number": 93,
      "bismillah_pre": true,
      "revelation_order": 11,
      "revelation_place": "مكية",
      "name_complex": "Ađ-Đuĥaá",
      "name_arabic": "الضحى",
      "name_simple": "Ad-Duhaa",
      "verses_count": 11,
      "pages": [596, 596],
      "translated_name": {
        "language_name": "english",
        "name": "The Morning Hours",
      },
    },
    {
      "id": 94,
      "surah_number": 94,
      "bismillah_pre": true,
      "revelation_order": 12,
      "revelation_place": "مكية",
      "name_complex": "Ash-Sharĥ",
      "name_arabic": "الشرح",
      "name_simple": "Ash-Sharh",
      "verses_count": 8,
      "pages": [596, 596],
      "translated_name": {"language_name": "english", "name": "The Relief"},
    },
    {
      "id": 95,
      "surah_number": 95,
      "bismillah_pre": true,
      "revelation_order": 28,
      "revelation_place": "مكية",
      "name_complex": "At-Tīn",
      "name_arabic": "التين",
      "name_simple": "At-Tin",
      "verses_count": 8,
      "pages": [597, 597],
      "translated_name": {"language_name": "english", "name": "The Fig"},
    },
    {
      "id": 96,
      "surah_number": 96,
      "bismillah_pre": true,
      "revelation_order": 1,
      "revelation_place": "مكية",
      "name_complex": "Al-`Alaq",
      "name_arabic": "العلق",
      "name_simple": "Al-'Alaq",
      "verses_count": 19,
      "pages": [597, 597],
      "translated_name": {"language_name": "english", "name": "The Clot"},
    },
    {
      "id": 97,
      "surah_number": 97,
      "bismillah_pre": true,
      "revelation_order": 25,
      "revelation_place": "مكية",
      "name_complex": "Al-Qadr",
      "name_arabic": "القدر",
      "name_simple": "Al-Qadr",
      "verses_count": 5,
      "pages": [598, 598],
      "translated_name": {"language_name": "english", "name": "The Power"},
    },
    {
      "id": 98,
      "surah_number": 98,
      "bismillah_pre": true,
      "revelation_order": 100,
      "revelation_place": "مدنية",
      "name_complex": "Al-Bayyinah",
      "name_arabic": "البينة",
      "name_simple": "Al-Bayyinah",
      "verses_count": 8,
      "pages": [598, 599],
      "translated_name": {
        "language_name": "english",
        "name": "The Clear Proof",
      },
    },
    {
      "id": 99,
      "surah_number": 99,
      "bismillah_pre": true,
      "revelation_order": 93,
      "revelation_place": "مدنية",
      "name_complex": "Az-Zalzalah",
      "name_arabic": "الزلزلة",
      "name_simple": "Az-Zalzalah",
      "verses_count": 8,
      "pages": [599, 599],
      "translated_name": {"language_name": "english", "name": "The Earthquake"},
    },
    {
      "id": 100,
      "surah_number": 100,
      "bismillah_pre": true,
      "revelation_order": 14,
      "revelation_place": "مكية",
      "name_complex": "Al-`Ādiyāt",
      "name_arabic": "العاديات",
      "name_simple": "Al-'Adiyat",
      "verses_count": 11,
      "pages": [599, 600],
      "translated_name": {"language_name": "english", "name": "The Courser"},
    },
    {
      "id": 101,
      "surah_number": 101,
      "bismillah_pre": true,
      "revelation_order": 30,
      "revelation_place": "مكية",
      "name_complex": "Al-Qāri`ah",
      "name_arabic": "القارعة",
      "name_simple": "Al-Qari'ah",
      "verses_count": 11,
      "pages": [600, 600],
      "translated_name": {"language_name": "english", "name": "The Calamity"},
    },
    {
      "id": 102,
      "surah_number": 102,
      "bismillah_pre": true,
      "revelation_order": 16,
      "revelation_place": "مكية",
      "name_complex": "At-Takāthur",
      "name_arabic": "التكاثر",
      "name_simple": "At-Takathur",
      "verses_count": 8,
      "pages": [600, 600],
      "translated_name": {
        "language_name": "english",
        "name": "The Rivalry in world increase",
      },
    },
    {
      "id": 103,
      "surah_number": 103,
      "bismillah_pre": true,
      "revelation_order": 13,
      "revelation_place": "مكية",
      "name_complex": "Al-`Aşr",
      "name_arabic": "العصر",
      "name_simple": "Al-'Asr",
      "verses_count": 3,
      "pages": [601, 601],
      "translated_name": {
        "language_name": "english",
        "name": "The Declining Day",
      },
    },
    {
      "id": 104,
      "surah_number": 104,
      "bismillah_pre": true,
      "revelation_order": 32,
      "revelation_place": "مكية",
      "name_complex": "Al-Humazah",
      "name_arabic": "الهمزة",
      "name_simple": "Al-Humazah",
      "verses_count": 9,
      "pages": [601, 601],
      "translated_name": {"language_name": "english", "name": "The Traducer"},
    },
    {
      "id": 105,
      "surah_number": 105,
      "bismillah_pre": true,
      "revelation_order": 19,
      "revelation_place": "مكية",
      "name_complex": "Al-Fīl",
      "name_arabic": "الفيل",
      "name_simple": "Al-Fil",
      "verses_count": 5,
      "pages": [601, 601],
      "translated_name": {"language_name": "english", "name": "The Elephant"},
    },
    {
      "id": 106,
      "surah_number": 106,
      "bismillah_pre": true,
      "revelation_order": 29,
      "revelation_place": "مكية",
      "name_complex": "Quraysh",
      "name_arabic": "قريش",
      "name_simple": "Quraysh",
      "verses_count": 4,
      "pages": [602, 602],
      "translated_name": {"language_name": "english", "name": "Quraysh"},
    },
    {
      "id": 107,
      "surah_number": 107,
      "bismillah_pre": true,
      "revelation_order": 17,
      "revelation_place": "مكية",
      "name_complex": "Al-Mā`ūn",
      "name_arabic": "الماعون",
      "name_simple": "Al-Ma'un",
      "verses_count": 7,
      "pages": [602, 602],
      "translated_name": {
        "language_name": "english",
        "name": "The Small Kindesses",
      },
    },
    {
      "id": 108,
      "surah_number": 108,
      "bismillah_pre": true,
      "revelation_order": 15,
      "revelation_place": "مكية",
      "name_complex": "Al-Kawthar",
      "name_arabic": "الكوثر",
      "name_simple": "Al-Kawthar",
      "verses_count": 3,
      "pages": [602, 602],
      "translated_name": {"language_name": "english", "name": "The Abundance"},
    },
    {
      "id": 109,
      "surah_number": 109,
      "bismillah_pre": true,
      "revelation_order": 18,
      "revelation_place": "مكية",
      "name_complex": "Al-Kāfirūn",
      "name_arabic": "الكافرون",
      "name_simple": "Al-Kafirun",
      "verses_count": 6,
      "pages": [603, 603],
      "translated_name": {
        "language_name": "english",
        "name": "The Disbelievers",
      },
    },
    {
      "id": 110,
      "surah_number": 110,
      "bismillah_pre": true,
      "revelation_order": 114,
      "revelation_place": "مدنية",
      "name_complex": "An-Naşr",
      "name_arabic": "النصر",
      "name_simple": "An-Nasr",
      "verses_count": 3,
      "pages": [603, 603],
      "translated_name": {
        "language_name": "english",
        "name": "The Divine Support",
      },
    },
    {
      "id": 111,
      "surah_number": 111,
      "bismillah_pre": true,
      "revelation_order": 6,
      "revelation_place": "مكية",
      "name_complex": "Al-Masad",
      "name_arabic": "المسد",
      "name_simple": "Al-Masad",
      "verses_count": 5,
      "pages": [603, 603],
      "translated_name": {"language_name": "english", "name": "The Palm Fiber"},
    },
    {
      "id": 112,
      "surah_number": 112,
      "bismillah_pre": true,
      "revelation_order": 22,
      "revelation_place": "مكية",
      "name_complex": "Al-'Ikhlāş",
      "name_arabic": "الإخلاص",
      "name_simple": "Al-Ikhlas",
      "verses_count": 4,
      "pages": [604, 604],
      "translated_name": {"language_name": "english", "name": "The Sincerity"},
    },
    {
      "id": 113,
      "surah_number": 113,
      "bismillah_pre": true,
      "revelation_order": 20,
      "revelation_place": "مكية",
      "name_complex": "Al-Falaq",
      "name_arabic": "الفلق",
      "name_simple": "Al-Falaq",
      "verses_count": 5,
      "pages": [604, 604],
      "translated_name": {"language_name": "english", "name": "The Daybreak"},
    },
    {
      "id": 114,
      "surah_number": 114,
      "bismillah_pre": true,
      "revelation_order": 21,
      "revelation_place": "مكية",
      "name_complex": "An-Nās",
      "name_arabic": "الناس",
      "name_simple": "An-Nas",
      "verses_count": 6,
      "pages": [604, 604],
      "translated_name": {"language_name": "english", "name": "The Mankind"},
    },
  ];
}
